# Site settings
title: Refined Bits Podcast
description: "A monthly podcast about becoming a better author of code."
email: refinedbits@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
baseurl: ''
