# Site settings
title: Refined Bits Podcast
description: A monthly podcast about becoming a better author of code.
email: refinedbits@gmail.com
authors: Andrew Bates, Bryce Handerson, and Chris Antes

# Build settings
timezone: America/Los_Angeles
markdown: kramdown
permalink: pretty
url: http://refinedbitspodcast.com
baseurl:
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock']
sass:
    style: :compressed
